
version: "3.3"

services:
  jupyter:
    build:
      context: .
    # To use a different port of host, change the first 8888.
    ports:
      - "8888:8888"
    volumes:
      - type: "bind"
        source: ./../../examples
        target: /examples
  mysql:
    image: mysql:5.7
    # To use a different port of host, change the first 8888.
    ports:
      - "13306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
